spring:
  datasource:
    url: jdbc.mysql:///spring-boot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: #指定mybatis的核心配置文件
  mapper-locations:
     classpath:
       mapper/*Mapper.xml  #mybatis的映射文件路径
  type-aliases-package: com.huangchuan.springmybatis.pojo.User   #对那个路径下的包取别名
